---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mydb
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/chart-image: glob:master-*
spec:
  releaseName: mydb
  chart:
    git: ssh://git@github.com/avielb/test-flux.git
    ref: master
    path: app
  values:
    env:
      AA: TEST_AA
      BB: TEST_BB
      CC: TEST_CC
      DEMO: not_working
    image:
      repository: avielb/test-flux
      tag: master-9999

